### ISSUE TITLE
Invalid parameter value for redirect_uri: Missing authority: file://

### ISSUE THREAD

**Issue by gaithoben** [ronzeidman/ng2-ui-auth-example#10]
Please help, when testing my app with ionic serve on browser, it works well. Not until i take the app on the device and i get the above error trying to authenticate with google.

Thank you in advance.

**Comment by royipressburger** [comment]
Hi @gaithoben try to take a look [here](https://github.com/ronzeidman/ng2-ui-auth/issues/52).
If you still having issue let me know. This issue it talking about facebook but it should be the same with google. 
One difference I know is the callback URL in google you dont need the `http://localhots/`. `http://localhost` is enough from what i remember.
