### ISSUE TITLE
Where to put Server URL

### ISSUE THREAD

**Issue by tomNjerry** [ronzeidman/ng2-ui-auth-example#11]
As I came from **Satellizer** to this, we have '_base_url_' parameter there which tells **Satellizer** about our local server and post things there for server side validation.
**Where to put that URL ??**

**Comment by godlovesugly** [comment]
@tomNjerry In this file https://github.com/ronzeidman/ng2-ui-auth-example/blob/master/client/src/config.ts

Do it like this:
`export class MyAuthConfig extends CustomConfig {
    defaultHeaders = {'Content-Type': 'application/json'};
    baseUrl = env.apiBaseUrl;
...
}`
