### ISSUE TITLE
No import found

### ISSUE THREAD

**Issue by tomNjerry** [ronzeidman/ng2-ui-auth-example#17]
When trying to import CustomConfig from ng2-ui-auth in ionic 3 project
it is giving error of having no exported member from ng2-ui-auth from node_module

**Comment by ronzeidman** [comment]
This repository (the example) is a bit outdated. now there is no need to create a config class, just pass an object that implements the interface `IPartialConfigOptions` https://github.com/ronzeidman/ng2-ui-auth/blob/master/src/config.service.ts#L69

**Comment by nigel-dewar** [comment]
Hi Ron,

Can we please get an updated example?  Working with say Angular 5. Ionic 3.

Cheers

Nige

**Comment by ronzeidman** [comment]
updated the repo (I'm not using ionic so only angular)

**Comment by nigel-dewar** [comment]
Thanks Ron. Cheers!!!

**Comment by nigel-dewar** [comment]
Did somebody else put the ionic2 project in here Ron?

**Comment by ronzeidman** [comment]
Yes, it was @royipressburger you can look at the pull requests.

**Comment by nigel-dewar** [comment]
Cool thanks Ron

Cheers. Enjoy the break buy the way. Hope 2018 goes great for you.


Sent from Samsung Mobile


-------- Original message --------
From: Ron Zeidman
Date:27/12/2017 18:20 (GMT+10:00)
To: ronzeidman/ng2-ui-auth-example
Cc: Nigel Dewar , Comment
Subject: Re: [ronzeidman/ng2-ui-auth-example] No import found (#17)


Yes, it was @royipressburger<https://github.com/royipressburger> you can look at the pull requests.

**Comment by geminiyellow** [comment]
looks like nobody will update the ionic example. it is out of date. 

it use "ng2-ui-auth": "^6.2.0", but now is "ng2-ui-auth": "^8.0.1",

**Comment by ronzeidman** [comment]
@geminiyellow
You are welcome to send a PR when you figure out.
If you have any questions about the core functionality or you get stuck somewhere I'd be happy to help.
