### ISSUE TITLE
Facebook 3-legged login

### ISSUE THREAD

**Issue by JoanRoucoux** [ronzeidman/ng2-ui-auth-example#4]
Hi,

Is there a way to implement the Facebook 3-legged authentication (like Twitter) ?

I like the way you did it for Twitter because both keys are on the server. I tried to do the same for Facebook following how you did it for Twitter but cannot make it to work properly...

Thanks :)

**Comment by ronzeidman** [comment]
Hi, sorry, It's a pretty busy month. I'll get to it when I have more time, I will also update the example. Don't know when it will be though.

**Comment by JoanRoucoux** [comment]
Hi, sure no problem ! I'm working with VKontakte right now, I'll maybe commit my code as an example of custom provider if it works.

**Comment by ronzeidman** [comment]
Great! thanks.
