### ISSUE TITLE
Quick question about ionic

### ISSUE THREAD

**Issue by speedfl** [ronzeidman/ng2-ui-auth-example#7]
Hello.

First of all thanks a lot for your updates on this project and for the example you created. Howevet I have small questions about ionic : 
- I don't see like in your client project a login with social (like the google one)
We would nees inapp browser no like on the satellizer project ? 

Thanks for your answer

**Comment by ronzeidman** [comment]
Can you elaborate what you mean by: "We would nees inapp browser no like on the satellizer project"

@royipressburger can you help?

**Comment by speedfl** [comment]
sorry it is a typo because of my phone

In fact I would like to know if we would need the cordova plugin inapp browser like in satellizer.

To be honnest I never used satellizer. I am working on Ionic 2 so when I saw your project I run on it and started trying to understand. I followed the complete flow but facebook is not called when I am running ionic serve

**Comment by speedfl** [comment]
So basically what I did:

Clone the repo.
Did npm install on the ionic folder

Some changes as in fact there is only the basic login

ng2-ui-auth-example\ionic2\src\pages\login\login.html => <button ion-button (click)="signup()">Signup</button>

ng2-ui-auth-example\ionic2\src\pages\signup\signup.html => <button ion-button (click)="signup('facebook')">Login facebook</button>

g2-ui-auth-example\ionic2\src\pages\signup\signup.ts => 

     signup(provider){
      console.debug('launch signup');
      this.auth.authenticate(provider);
     }

So Working with ionic serve. Just to know if it we need to use the inapp browser and how to use it of cordova :)

**Comment by royipressburger** [comment]
Hi @speedfl, if you use this library you will the in app browser.
The steps to work with facebook:
1. Make sure you redirect url us `http://localhost/` NOTE that the `/`at the end is mandatory
2. Install `cordova-inappbrowser`
3. Make sure that on Facebook console you add the url `http://localhost/`

Hope this helps

**Comment by speedfl** [comment]
Thx I will try to follow your explanation

**Comment by speedfl** [comment]
Euh just another question.
I did a java auth server using jaxrs (based on the example provided by satellizer with some changes to map my need)
However I am getting error.
Unrecognized field 'url' not marked as ignorable
It is due to the fact that I am receiving in my request a field called url and I am trying to map in an object which does not contain it.
Could you please tell me where I can find the full content of the request sent to the server for facebook login ?

**Comment by royipressburger** [comment]
The request you are talking about is from the ui to your server after the authentication with Facebook?

**Comment by speedfl** [comment]
Yes.

What is sent is:

`{
	"name": "facebook",
	"url": "/auth/facebook",
	"authorizationEndpoint": "https://www.facebook.com/v2.5/dialog/oauth",
	"redirectUri": "http://localhost:8100/",
	"requiredUrlParams": [
		"display", "scope"
	],
	"scope": [
		"email"
	],
	"scopeDelimiter": ",",
	"display": "popup",
	"oauthType": "2.0",
	"popupOptions": {
		"width": 580,
		"height": 400
	},
	"clientId": "221171324975919",
	"defaultUrlParams": [
		"response_type", "client_id", "redirect_uri"
	],
	"responseType": "code",
	"responseParams": {
		"code": "code",
		"clientId": "clientId",
		"redirectUri": "redirectUri"
	},
	"code": "AQDigBHYBb2q-0t2s0xOP9PpaCPYroJG9p9TqQzSAWFHRmo9l4l6Ecp2B7bv96KJZZ2qzz3ub4hkNTn4034FfQXWMoJQTzixPY1JtqSo5V7bjFjGV0OWBFbBjUkSYywmDp-TufqADEwWk34eT4gIDmmlLkQiiFUinXpkMFeokJSaBnzi7DRiZT8R_sjLntMuZBcKDSoBVHSiwZTS2PS4jdt2aFaDE-y9f5T92bsxiQNm17h5Qfk0fbDTTVXl2iZwkIETVMjG2OpbZ2tumCpv8oj_yaI_NATmdwWejY39rELfC1TeMHgOaEFAhIRV6TxedFE",
	"_": "_"
}`

I do not understand why my code is crashing but it do not seems to be linked to you :)

**Comment by speedfl** [comment]
So you can close the issue :) sorry for the inconveniance

What is sent is:

{ "name": "facebook", "url": "/auth/facebook", "authorizationEndpoint": "https://www.facebook.com/v2.5/dialog/oauth", "redirectUri": "http://localhost:8100/", "requiredUrlParams": [ "display", "scope" ], "scope": [ "email" ], "scopeDelimiter": ",", "display": "popup", "oauthType": "2.0", "popupOptions": { "width": 580, "height": 400 }, "clientId": "CLIENT_ID", "defaultUrlParams": [ "response_type", "client_id", "redirect_uri" ], "responseType": "code", "responseParams": { "code": "code", "clientId": "clientId", "redirectUri": "redirectUri" }, "code": "THE CODE HERE", "_": "_" }

I finally understood what is happening. 
I made a fix. If you want to have an example using jaxrs for the server don't hesitate to ask me :)

**Comment by royipressburger** [comment]
Cool.. good luck

**Comment by ronzeidman** [comment]
Thanks @royipressburger

**Comment by speedfl** [comment]
@royipressburger   I would just have a little question. I installed the inappbrowser and it seems to be launched

However I am getting issue:
The redirect_uri is not supported

If I am looking at the redirect_uri sent I am getting : redirect_uri=file:///

The issue only occures when I am connecting on my device. On browser with ionic serve everything is working.

Is there specific things to do?

**Comment by royipressburger** [comment]
@speedfl Did you extend the `CustomConfig` and changed to redirect_uri?

```js

export class MyConfig extends CustomConfig {
    providers = {
      facebook: {
        clientId: CONFIG.FACEBOOK_KEY,
        scope: CONFIG.FACEBOOK_PERMISSION,
        redirectUri: 'http://localhost/'

       }
    };
}
```

**Comment by speedfl** [comment]
Hello 
Sorry I thought I had to put it only on the Facebook developer page (on my app)
I will try,

Thanks a lot :)

I will keep you posted.

**Comment by speedfl** [comment]
works!! Thanks a lot!

**Comment by royipressburger** [comment]
@speedfl any time bro!! good luck
